### ISSUE TITLE
extension broken

### ISSUE THREAD

**Issue by tristan-k** [robbiev/multipass-chrome#1]
I'm using 1Password 4.4.3 and Ubuntu 14.04 LTS. I followed your instructions and made a symlink on $HOME/Dropbox/1password/1Password.agilekeychain/ to the path of my Keychain. I then installed your extension through the Chrome Web Store and invoked it with the key combo. It keeps asking for my password, even though I entered it. Hitting the "Return"-Key as a confirmation does nothting. Could your extension be broken?

**Comment by robbiev** [comment]
This happens when you type a wrong password (there is no proper feedback ATM) or something else went wrong.

The package on the Chrome web store is an older version, I haven't updated it in a while because the interface sucks and nobody has complained. Maybe try running the latest extension from source, which is what I do.

To generate the JS code, first install NPM, then:

```
sudo npm install -g react-tools@0.11.1
cd extension && jsx rsrc rbin
```

First unload / uninstall the extension if you still have it installed.

Now go to `chrome://extensions` in Chrome, enable developer mode (checkbox top right) and click "Load unpacked extension", select the "extension" directory in this repo

After the extension is loaded, it will list an extension ID (e.g. `ID: dpjcjabajojbeefkfgcbnadgeeiloipd`). Copy this to the clipboard.

Try using the go binary from the release zip (I'm not 100% sure it is compatible, the alternative is to install go, set the $GOPATH, clone this repo into the proper $GOPATH location, `go get -v ./...` and `make`). In the release package, update the `org.garbagecollected.multipass.json` file to use the extension ID you copied (in the `allowed_origins` section). Then run the install script as before: `sudo ./install.sh`

If this does not resolve your issue you'll need to try building the go binary with logging enabled (`go build -tags log` will make it append to `~/multipass_log.txt`) so we can get some debug info. For security reasons this feature is not included in the release binary.

You can also try debugging the chrome extension, I think it prints some details to the JS console.

Hope this helps, let me know how you get on!

**Comment by robbiev** [comment]
Haven't heard back in a while so closing this - let me know how you got on.
